client_config_backend: settings
client_config_backend: file
client_config:
    client_id: 900587685282-ajjkpt81eag8ejr38msha5r4smb8sn6u.apps.googleusercontent.com
    client_secret: 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

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
    - https://www.googleapis.com/auth/drive
    - https://www.googleapis.com/auth/drive.install